export default {
    AGENCY_LIST_RECEIVED: 'AGENCY_LIST_RECEIVED',
    AGENCY_LIST_REQUESTED: 'AGENCY_LIST_REQUESTED',

    AGENCY_ROUTES_REQUESTED: 'AGENCY_ROUTES_REQUESTED',
    AGENCY_ROUTES_RECEIVED: 'AGENCY_ROUTES_RECEIVED'
}